antirabstvo/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from news import views as news_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', news_views.NewsListView.as_view(), name='index'),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^resumes/', include('resumes.urls', namespace='resumes')),
    url(r'^vacancies/', include('vacancies.urls', namespace='vacancies')),
    url(r'^questions/', include('questions.urls', namespace='questions')),
    url(r'^news/', include('news.urls', namespace='news')),
    url(r'^courses/', include('courses.urls', namespace='courses')),
    url(r'^products/', include('products.urls', namespace="products"))
] \
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

courses/urls.py
from django.conf.urls import url
from django.core.urlresolvers import reverse

from . import views

urlpatterns = [
    url(r'^my/$', views.my_courses, name='my_courses'),
    url(r'^course/(?P<pk>[0-9]+)/', views.course_page, name='course_detail'),
    url(r'^section/(?P<pk>[0-9]+)/', views.section_page, name='section_detail'),
    url(r'^next-section/(?P<pk>[0-9]+)/', views.next_section, name='next_section')
]

news/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^news/(?P<pk>[0-9]+)/', views.NewsDetailView.as_view(), name='view_news'),
    url(r'^/$', views.NewsListView.as_view(), name='all_news'),
]

questions/urls.py
from django.conf.urls import url
from django.core.urlresolvers import reverse

from . import views

urlpatterns = [
    url(r'^all/$', views.all_questions, name='all_questions'),
    url(r'^add-question/$', views.add_question, name='add_question'),
    url(r'^question/(?P<pk>[0-9]+)/', views.view_question, name='view_question'),
    url(r'^answer/(?P<pk>[0-9]+)/', views.answer_question, name='answer_question'),
    url(r'^delete-question/(?P<pk>[0-9]+)/', views.delete_question, name='delete_question'),
    url(r'^category/(?P<category>[a-z]+)/', views.show_category, name='show_category')
]

resumes/urls.py
from django.conf.urls import url
from django.core.urlresolvers import reverse

from . import views

urlpatterns = [
    url(r'^add-resume/$', views.AddResumeView.as_view(), name='add_resume'),
    url(r'^my-resumes/$', views.MyResumesView.as_view(), name='my_resumes'),
    url(r'^resume/(?P<pk>[0-9]+)/', views.ResumeDetailView.as_view(), name='view_resume'),
    url(r'^all-resumes/$', views.ResumeListView.as_view(), name='all_resumes'),
    url(r'^delete-resume/', views.DeleteResumeView.as_view(), name='delete_resume'),
    url(r'^set-resume-status/', views.SetStatusView.as_view(), name='set_status'),
    url(r'^update-resume/(?P<pk>[0-9]+)/', views.ResumeUpdateView.as_view(), name='change_resume')
]

users/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login

from . import views

urlpatterns = [
    url(r'^login/$', login, {'template_name': 'users/login.html'}, name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^register/$', views.register, name='register'),
    url(r'^courses/$', views.courses, name='courses'),
    url(r'^profile/(?P<id>[0-9]+)/', views.profile, name='profile'),
]

antirabstvo/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'antirabstvo/index.html')

antirabstvo/templates/antirabstvo/base.html
{% load staticfiles %}
{% load user_filters %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'index' %}">Антирабство</a>
            </div>
            <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li><a href="#">Что это такое?</a></li>
                <li><a href="#about">Наши курсы</a></li>
                {% if user.is_authenticated %}
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Профиль {{ user.username }} <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'users:profile' user.id %}">Мой профиль</a></li>
                            {% if user.is_employer %}
                            <li><a href="{% url 'vacancies:my_vacancies' %}">Мои вакансии</a></li>
                            <li><a href="{% url 'resumes:all_resumes' %}">Поиск соискателей</a></li>
                            {% else %}
                            <li><a href="{% url 'courses:my_courses' %}">Мои курсы</a></li>
                            <li><a href="{% url 'resumes:my_resumes' %}">Мои резюме</a></li>
                            <li><a href="{% url 'vacancies:all_vacancies' %}">Поиск вакансий</a></li>
                            {% endif %}
                            <li><a href="{% url 'users:logout' %}">Выход</a></li>
                        </ul>
                    </li>
                {% else %}
                    <li><a href="{% url 'users:login' %}">Вход</a></li>
                {% endif %}
                <li><a href="">Компаниям</a></li>
                <li><a href="{% url 'questions:all_questions' %}">Вопрос-ответ</a></li>
                <li><a href="">?</a></li>
            </ul>
            </div><!--/.nav-collapse -->
        </div>
    </nav>
    <div class="container main_content">
        {% block content %}{% endblock content %}
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script>
      function getCookie(name) {
          var cookieValue = null;
          if (document.cookie && document.cookie !== '') {
              var cookies = document.cookie.split(';');
              for (var i = 0; i < cookies.length; i++) {
                  var cookie = jQuery.trim(cookies[i]);
                  // Does this cookie string begin with the name we want?
                  if (cookie.substring(0, name.length + 1) === (name + '=')) {
                      cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                      break;
                  }
              }
          }
          return cookieValue;
      }
      var csrftoken = getCookie('csrftoken');

      function csrfSafeMethod(method) {
          // these HTTP methods do not require CSRF protection
          return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
      }
      $.ajaxSetup({
          beforeSend: function(xhr, settings) {
              if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                  xhr.setRequestHeader("X-CSRFToken", csrftoken);
              }
          }
      });
    </script>
    {% block extra_scripts %}{% endblock extra_scripts %}
</body>
</html>