antirabstvo/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from news import views as news_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', news_views.NewsListView.as_view(), name='index'),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^resumes/', include('resumes.urls', namespace='resumes')),
    url(r'^vacancies/', include('vacancies.urls', namespace='vacancies')),
    url(r'^questions/', include('questions.urls', namespace='questions')),
    url(r'^news/', include('news.urls', namespace='news')),
    url(r'^courses/', include('courses.urls', namespace='courses')),
    url(r'^products/', include('products.urls', namespace="products"))
] \
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^news/(?P<pk>[0-9]+)/', views.NewsDetailView.as_view(), name='view_news'),
    url(r'^/$', views.NewsListView.as_view(), name='all_news'),
]

vacancies/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^add-vacancy/$', views.AddVacancyView.as_view(), name='add_vacancy'),
    url(r'^my-vacancies/$', views.MyVacanciesView.as_view(), name='my_vacancies'),
    url(r'^vacancy/(?P<pk>[0-9]+)/', views.VacancyDetailView.as_view(), name='view_vacancy'),
    url(r'^update-vacancy/(?P<pk>[0-9]+)/', views.VacancyUpdateView.as_view(), name='change_vacancy'),
    url(r'^delete-resume/', views.DeleteVacancyView.as_view(), name='delete_vacancy'),
    url(r'^all-vacancies/$', views.VacancyListView.as_view(), name='all_vacancies')
]

vacancies/models.py
from django.db import models
from users.models import User


class Vacancy(models.Model):
    STATUS_CHOICES = (
        ('published', 'Опубликовано'),
        ('hidden', 'Скрыто')
    )
    title = models.CharField(verbose_name="Заголовок вакансии", max_length=255)
    location = models.CharField(verbose_name="Местоположение", max_length=255, blank=True)
    type = models.CharField(verbose_name="Тип вакансии", max_length=100, choices=(
        ('Удаленная', 'Удаленная'),
        ('Постоянная', 'Постоянная'),
        ('Проектная', 'Проектная')
    ))
    email_for_resume = models.EmailField(max_length=100)
    description = models.TextField(verbose_name="Описание вакансии")
    company_name = models.CharField(verbose_name="Название компании", max_length=100)
    company_site = models.CharField(verbose_name="Сайт компании", max_length=100)
    company_logo = models.ImageField(verbose_name="Лого компании", upload_to='uploads/companies/photo/', blank=True)
    status = models.CharField(verbose_name="Статус", max_length=20, choices=STATUS_CHOICES, default='published')
    creator = models.ForeignKey('users.User', on_delete=models.CASCADE, verbose_name="Создатель")
    date_created = models.DateTimeField(auto_now_add=True, editable=False)
    date_changed = models.DateTimeField(auto_now=True, editable=False)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return "/vacancies/vacancy/%i/" % self.pk


class CompanyProfile(models.Model):
    user = models.OneToOneField(
        User,
        on_delete = models.CASCADE,
        primary_key = True
    )
    company_name = models.CharField(verbose_name="Название компании", max_length=100)
    company_site = models.CharField(verbose_name="Сайт компании", max_length=100)
    company_logo = models.ImageField(verbose_name="Лого компании", upload_to='uploads/companies/photo/', blank=True)

    def __str__(self):
        return self.company_name

vacancies/forms.py
from django.forms import ModelForm
from vacancies.models import Vacancy


class VacancyForm(ModelForm):
    class Meta:
        model = Vacancy
        fields = [
            'title',
            'location',
            'type',
            'email_for_resume',
            'description',
            'company_name',
            'company_site',
            'company_logo',
        ]

vacancies/views.py
from . import models
from vacancies.forms import VacancyForm
from users.decorators import user_is_employer
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView, FormView
from django.views import View
from django.utils.decorators import method_decorator


@method_decorator(login_required, name='dispatch')
@method_decorator(user_is_employer, name='dispatch')
class AddVacancyView(FormView):
    template_name = 'vacancies/add_vacancy.html'
    form_class = VacancyForm
    success_url = reverse_lazy('vacancies:my_vacancies')

    def form_valid(self, form):
        vacancy = form.save(commit=False)
        vacancy.creator = self.request.user
        vacancy.save()
        return super().form_valid(form)


@method_decorator(login_required, name='dispatch')
@method_decorator(user_is_employer, name='dispatch')
class MyVacanciesView(View):
    template_name = 'vacancies/my_vacancies.html'

    def get(self, request, *args, **kwargs):
        vacancies = models.Vacancy.objects.filter(creator=request.user)
        return render(request, self.template_name, {'vacancies': vacancies})


class VacancyListView(ListView):
    queryset = models.Vacancy.objects.filter(status='published')


class VacancyDetailView(DetailView):
    model = models.Vacancy


@method_decorator(login_required, name='dispatch')
@method_decorator(user_is_employer, name='dispatch')
class DeleteVacancyView(View):
    def post(self, request, *args, **kwargs):
        vacancy = models.Vacancy.objects.get(pk=request.POST['vacancy'])
        vacancy.delete()
        return JsonResponse({
            'status': 'ok',
        })


@method_decorator(login_required, name='dispatch')
@method_decorator(user_is_employer, name='dispatch')
class VacancyUpdateView(UpdateView):
    model = models.Vacancy
    fields = ['title', 'location', 'type', 'email_for_resume', 'description']
    template_name_suffix = '_update'

vacancies/templates/vacancies/add_vacancy.html
{% extends "antirabstvo/base.html" %}
{% block content %}
<form method="post" enctype="multipart/form-data" action="{% url 'vacancies:add_vacancy' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-default">Добавить</button>
</form>
{% endblock content %}

vacancies/templates/vacancies/my_vacancies.html
{% extends "antirabstvo/base.html" %}
{% block content %}
<a class="btn btn-primary" href="{% url 'vacancies:add_vacancy' %}" style="margin-bottom:20px" role="button">Добавить вакансию</a>
{% if vacancies.count > 0 %}
<table class="table table-striped">
    <tr>
        <th>Заголовок вакансии</th>
        <th>Дата добавления</th>
        <th>Дата изменения</th>
        <th>Действия</th>
    </tr>
    {% for vacancy in vacancies %}
    <tr id="vacancy-row-{{ vacancy.pk }}">
        <td><a href="{% url 'vacancies:view_vacancy' vacancy.pk %}">{{ vacancy }}</a></td>
        <td>{{ vacancy.date_created }}</td>
        <td>{{ vacancy.date_changed }}</td>
        <td>
            <a href="{% url 'vacancies:change_vacancy' vacancy.pk %}">Изменить</a>
            <a href="" id="delete" data-id="{{ vacancy.pk }}">Удалить</a>
        </td>
    </tr>
    {% endfor %}
</table>
{% endif %}
{% endblock content %}

{% block extra_scripts %}
<script>
    $('#delete').click(function(e){
        e.preventDefault();
        id = $(this).data('id')
        $.post(
            "{% url 'vacancies:delete_vacancy' %}",
            JSON.stringify({
                'vacancy': id,
            })
        ).done(function(msg){
            $('#vacancy-row-'+id).hide();
        });
    });
</script>
{% endblock extra_scripts %}

vacancies/templates/vacancies/vacancy_detail.html
{% extends "antirabstvo/base.html" %}
{% block content %}
<p>{{ object.title }}</p>
<p>{{ object.location }}</p>
<p>{{ object.type }}</p>
<p>{{ object.email_for_resume }}</p>
<p>{{ object.description }}</p>
<p>{{ object.company_name }}</p>
<p>{{ object.company_site }}</p>
{% if object.company_logo %}
    <p>{{ object.company_logo.url }}</p>
{% endif %}
<p>{{ object.date_created }}</p>
<p>{{ object.date_changed }}</p>
{% endblock content %}

vacancies/templates/vacancies/vacancy_list.html
{% extends "antirabstvo/base.html" %}
{% block content %}
{% if object_list.count > 0 %}
<table class="table table-striped">
    <tr>
        <th>Заголовок вакансии</th>
        <th>Тип</th>
        <th>Локация</th>
        <th>Компания</th>
        <th>Дата добавления</th>
        <th>Дата изменения</th>
    </tr>
    {% for vacancy in object_list %}
    <tr>
        <td><a href="{% url 'vacancies:view_vacancy' vacancy.pk %}">{{ vacancy }}</a></td>
        <td>{{ vacancy.type }}</td>
        <td>{{ vacancy.location }}</td>
        <td>{{ vacancy.company_name }}</td>
        <td>{{ vacancy.date_created }}</td>
        <td>{{ vacancy.date_changed }}</td>
    </tr>
    {% endfor %}
</table>
{% endif %}
{% endblock content %}

vacancies/templates/vacancies/vacancy_update.html
{% extends "antirabstvo/base.html" %}
{% block content %}
<form method="post" enctype="multipart/form-data" action="">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-default">Изменить</button>
</form>
{% endblock content %}