antirabstvo/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from news import views as news_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', news_views.NewsListView.as_view(), name='index'),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^resumes/', include('resumes.urls', namespace='resumes')),
    url(r'^vacancies/', include('vacancies.urls', namespace='vacancies')),
    url(r'^questions/', include('questions.urls', namespace='questions')),
    url(r'^news/', include('news.urls', namespace='news')),
    url(r'^courses/', include('courses.urls', namespace='courses')),
    url(r'^products/', include('products.urls', namespace="products"))
] \
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^news/(?P<pk>[0-9]+)/', views.NewsDetailView.as_view(), name='view_news'),
    url(r'^/$', views.NewsListView.as_view(), name='all_news'),
]

products/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^(?P<pk>[0-9]+)/', views.ProductDetailView.as_view(), name='view_product'),
    url(r'^add-to-cart/$', views.add_to_cart, name='add_to_cart'),
    url(r'^cart/$', views.display_cart, name='cart'),
    url(r'^remove-from-cart/$', views.remove_from_cart, name='remove_from_cart'),
    url(r'^add-coupon/$', views.add_coupon, name='add_coupon'),
    url(r'^checkout/$', views.checkout, name='checkout')
]

products/models.py
from django.db import models


class Product(models.Model):
    STATUS_CHOICES = (
        ('published', 'Опубликовано'),
        ('hidden', 'Скрыто')
    )
    title = models.CharField(max_length=255, verbose_name="Название продукта")
    description = models.TextField(verbose_name="Описание продукта")
    image = models.ImageField(verbose_name="Картинка продукта", upload_to='uploads/products/images/', blank=True)
    price = models.IntegerField(verbose_name="Цена продукта")
    give_access_to = models.ForeignKey(
        'courses.Course',
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        verbose_name="Продукт даёт доступ к курсу:"
    )
    status = models.CharField(verbose_name="Статус", max_length=20, choices=STATUS_CHOICES, default='published')

    def __str__(self):
        return self.title


class Coupon(models.Model):
    code = models.CharField(max_length=20, verbose_name="Код купона")
    description = models.TextField(verbose_name="Описание")
    procent_num = models.IntegerField(verbose_name="Скидка в процентах")
    max_uses = models.IntegerField(verbose_name="Максимальное количество использований", null=True, blank=True)
    max_uses_for_user = models.IntegerField(verbose_name="Максимальное количество использований на пользователя", null=True, blank=True)
    coupon_date_end = models.DateField(verbose_name="Дата окончания купона", null=True, blank=True)
    products_to_use = models.ManyToManyField(
        'Product',
        null=True,
        blank=True,
        verbose_name="Скидка действует только на товары:",
        symmetrical=False
    )
    creator = models.ForeignKey('users.User', on_delete=models.SET_NULL, null=True, blank=True, verbose_name="Создатель")
    date_created = models.DateField(auto_now_add=True, editable=False)

    def __str__(self):
        return self.code


class Order(models.Model):
    STATUS_CHOICES = (
        ('new', 'Создан'),
        ('wait', 'Ожидается оплата'),
        ('cancel', 'Отменен'),
        ('success', 'Выполнен')
    )
    user = models.ForeignKey('users.User', on_delete=models.SET_NULL, null=True, verbose_name="Покупатель")
    used_coupon = models.CharField(verbose_name="Использованный купон", max_length=20, null=True, blank=True)
    gift_order = models.BooleanField(default=False, verbose_name="Курс в подарок")
    to_email = models.CharField(verbose_name="Емейл получателя купона", max_length=100, blank=True, null=True)
    message = models.TextField(verbose_name="Сообщение получателю купона", blank=True, null=True)
    products = models.ManyToManyField(Product)
    order_summ = models.IntegerField(verbose_name="Сумма заказа")
    status = models.CharField(verbose_name="Статус", max_length=20, choices=STATUS_CHOICES, default='new')
    date_created = models.DateField(auto_now_add=True, editable=False)

products/views.py
from django.shortcuts import render
from django.views.generic.detail import DetailView
from django.http import JsonResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from . import models
from courses import functions as cf


class ProductDetailView(DetailView):
    model = models.Product


def add_to_cart(request):
    post_data = request.POST
    order = models.Order.objects.filter(
        user=request.user,
        status='new'
    ).first() or None
    if order is None:
        order = models.Order(user=request.user, order_summ=0)
        order.save()
    product = models.Product.objects.get(pk=post_data['product_id'])
    if product in order.products.all():
        return JsonResponse({
            'status': 'error',
            'text': 'Продукт уже есть в корзине.'
        })
    order.products.add(product)
    order.order_summ += product.price
    order.save()
    return JsonResponse({
        'status': 'ok',
        'text': 'Продукт успешно добавлен в корзину.'
    })


def display_cart(request):
    cart = models.Order.objects.filter(
        user=request.user,
        status='new'
    ).first() or None
    return render(request, 'products/cart.html', {'cart': cart})


def remove_from_cart(request):
    post_data = request.POST
    order = models.Order.objects.filter(
        user=request.user,
        status='new'
    ).first() or None
    product = models.Product.objects.get(pk=post_data['product_id'])
    if product in order.products.all():
        order.products.remove(product)
        if len(order.products.all()) == 0:
            order.delete()
            return JsonResponse({
                'status': 'redirect',
                'text': 'Заказ удалён.'
            })
        else:
            recalculate_order(order)
    else:
        return JsonResponse({
            'status': 'error',
            'text': 'Данного продукта нет в вашем заказе.'
        })
    return JsonResponse({
        'status': 'ok',
        'text': 'Продукт удален из корзину.',
        'new_price': order.order_summ
    })


def checkout(request):
    order = models.Order.objects.filter(
        user=request.user,
        status='new'
    ).first()
    if order.order_summ == 0:
        for product in order.products.all():
            course = product.give_access_to
            if course is not None and cf.have_access_to_course(request.user, course) is None:
                cf.new_access_to_course(request.user, course)
    return HttpResponseRedirect(reverse('courses:my_courses'))


def recalculate_order(order):
    order.order_summ = 0
    if order.used_coupon is not None:
        coupon = models.Coupon.objects.filter(
            code=order.used_coupon
        ).first()
        for product in order.products.all():
            order.order_summ += product.price * (1 - (0.01 * coupon.procent_num))
    else:
        for product in order.products.all():
            order.order_summ += product.price
    order.save()


def add_coupon(request):
    post_data = request.POST
    order = models.Order.objects.get(pk=post_data['order_id'])
    coupon = models.Coupon.objects.filter(
        code=post_data['coupon']
    ).first() or None
    if coupon is None:
        return JsonResponse({
            'status': 'error',
            'text': 'Купона не существует.'
        })
    if order.used_coupon is None:
        order.user_coupon = coupon.code
        order.order_summ -= (order.order_summ * (0.01 * coupon.procent_num))
        order.save()
        return JsonResponse({
            'status': 'ok',
            'text': 'Купон ' + coupon.code + ' успешно добавлен к заказу.',
            'new_price': order.order_summ
        })
    else:
        return JsonResponse({
            'status': 'error',
            'text': 'Вы уже используете купон.'
        })

products/templates/products/cart.html
{% extends "antirabstvo/base.html" %}
{% block content %}
{% if cart %}
<span id="message-box"></span>
<table class="table table-striped">
    <tr>
        <th>Продукт</th>
        <th>Цена</th>
        <th></th>
    </tr>
    {% for product in cart.products.all %}
    <tr class="product_line_{{ product.pk }}">
        <td>{{ product.title }}</td>
        <td>{{ product.price }}</td>
        <td><a href="javascript:void(0)" id="remove_from_cart" data-id="{{ product.pk }}">Удалить</a></td>
    </tr>
    {% endfor %}
</table>
<label for="coupon">Введите купон</label>
<input type="text" id="coupon" name="coupon" placeholder="Код купона">
<a href="javascript:void(0)" data-order-id="{{ cart.pk }}" id="enter-coupon">Принять</a>
<p>Всего к оплате: <span id="summ">{{ cart.order_summ }}</span> р.</p>
<a href="javascript:void(0)" id="pay" class="btn btn-primary">Оплатить</a>
{% else %}
<p>Ваша корзина пуста</p>
{% endif %}
{% endblock content %}


{% block extra_scripts %}
<script type="text/javascript">
$('#enter-coupon').click(function(e){
    e.preventDefault();
    $.post(
        "{% url 'products:add_coupon' %}",
        {
            'order_id': $(this).data('order-id'),
            'coupon': $('#coupon').val()
        },
        function(data) {
            $('#message-box').text(data.text);
            $('#summ').text(data.new_price);
        });
});
$('#remove_from_cart').click(function(e){
    e.preventDefault();
    $.post(
        "{% url 'products:remove_from_cart' %}",
        {
            'product_id': $(this).data('id'),
        },
        function(data) {
            if(data.status == 'redirect') {
                document.location.href='/';
            } else {
                $('#message-box').text(data.text);
                $('#summ').text(data.new_price);
            }
        });
});
$('#pay').click(function(e){
    e.preventDefault();
    if($('#summ').text() == '0') {
        document.location.href='{% url 'products:checkout' %}';
    }
});
</script>
{% endblock extra_scripts %}

products/templates/products/product_detail.html
{% extends "antirabstvo/base.html" %}
{% block content %}
<div class="product" style="margin-bottom:15px;">
    <h2>{{ object.title }}</h2>
    <input type="hidden" name="product_id" value="{{ object.pk }}"/>
    {% if object.image %}
    <img src="{{ object.image.url }}" />
    {% endif %}
    <p style="padding-top:20px">{{ object.description }}</p>
    <p>Цена {{ object.price }} р.</p>
    <a href="#" id="add-to-cart" class="btn btn-success">Добавить в корзину</a>
    <span id="message"></span>
    <a href="{% url 'products:cart' %}" id="go-to-cart" style="display:none">Перейти в корзину</a>
</div>
{% endblock content %}

{% block extra_scripts %}
<script type="text/javascript">
$('#add-to-cart').click(function(e){
    e.preventDefault();
    $.post(
        "{% url 'products:add_to_cart' %}",
        {'product_id': $('input[name="product_id"]').val()},
        function(data) {
            $('#add-to-cart').hide();
            $('#message').text(data.text);
            $('#go-to-cart').show();
        });
});
</script>
{% endblock extra_scripts %}