antirabstvo/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from news import views as news_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', news_views.NewsListView.as_view(), name='index'),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^resumes/', include('resumes.urls', namespace='resumes')),
    url(r'^vacancies/', include('vacancies.urls', namespace='vacancies')),
    url(r'^questions/', include('questions.urls', namespace='questions')),
    url(r'^news/', include('news.urls', namespace='news')),
    url(r'^courses/', include('courses.urls', namespace='courses')),
    url(r'^products/', include('products.urls', namespace="products"))
] \
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^news/(?P<pk>[0-9]+)/', views.NewsDetailView.as_view(), name='view_news'),
    url(r'^/$', views.NewsListView.as_view(), name='all_news'),
]

questions/urls.py
from django.conf.urls import url
from django.core.urlresolvers import reverse

from . import views

urlpatterns = [
    url(r'^all/$', views.all_questions, name='all_questions'),
    url(r'^add-question/$', views.add_question, name='add_question'),
    url(r'^question/(?P<pk>[0-9]+)/', views.view_question, name='view_question'),
    url(r'^answer/(?P<pk>[0-9]+)/', views.answer_question, name='answer_question'),
    url(r'^delete-question/(?P<pk>[0-9]+)/', views.delete_question, name='delete_question'),
    url(r'^category/(?P<category>[a-z]+)/', views.show_category, name='show_category')
]

resumes/urls.py
from django.conf.urls import url
from django.core.urlresolvers import reverse

from . import views

urlpatterns = [
    url(r'^add-resume/$', views.AddResumeView.as_view(), name='add_resume'),
    url(r'^my-resumes/$', views.MyResumesView.as_view(), name='my_resumes'),
    url(r'^resume/(?P<pk>[0-9]+)/', views.ResumeDetailView.as_view(), name='view_resume'),
    url(r'^all-resumes/$', views.ResumeListView.as_view(), name='all_resumes'),
    url(r'^delete-resume/', views.DeleteResumeView.as_view(), name='delete_resume'),
    url(r'^set-resume-status/', views.SetStatusView.as_view(), name='set_status'),
    url(r'^update-resume/(?P<pk>[0-9]+)/', views.ResumeUpdateView.as_view(), name='change_resume')
]

resumes/models.py
from django.db import models
from django.core.urlresolvers import reverse

class Resume(models.Model):
    STATUS_CHOICES = (
        ('published', 'Опубликовано'),
        ('hidden', 'Скрыто')
    )
    fio = models.CharField(verbose_name="ФИО", max_length=100)
    email = models.EmailField(max_length=100)
    title = models.CharField(verbose_name="Заголовок резюме", max_length=255)
    location = models.CharField(verbose_name="Место поиска работы", max_length=255, blank=True)
    photo = models.ImageField(verbose_name="Фотография", upload_to='uploads/user_resume/photo/', blank=True)
    industry = models.CharField(verbose_name="Отрасль", max_length=100, choices=(
        ('E-commerce', 'E-commerce'),
        ('Авиация', 'Авиация')
    ))
    summary = models.TextField(verbose_name="Саммари", blank=True)
    resume_file = models.FileField(verbose_name="Файл резюме", upload_to='uploads/user_resume/')
    skills = models.TextField(verbose_name="Навыки", blank=True)
    experience = models.CharField(verbose_name="Опыт работы", max_length=20, choices=(
        ('до 1 года', 'до 1 года'),
        ('от 1-3 лет', 'от 1-3 лет'),
        ('от 3-5 лет', 'от 3-5 лет'),
        ('более 5 лет', 'более 5 лет')
    ))
    status = models.CharField(verbose_name="Статус", max_length=20, choices=STATUS_CHOICES, default='published')
    creator = models.ForeignKey('users.User', on_delete=models.CASCADE, verbose_name="Создатель")
    date_created = models.DateTimeField(auto_now_add=True, editable=False)
    date_changed = models.DateTimeField(auto_now=True, editable=False)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('resumes:view_resume', self.pk)

    def get_status_name(self):
        return self.get_status_display()

resumes/forms.py
from django.forms import ModelForm
from resumes.models import Resume


class ResumeForm(ModelForm):
    class Meta:
        model = Resume
        fields = [
            'fio',
            'email',
            'title',
            'location',
            'photo',
            'industry',
            'summary',
            'resume_file',
            'skills',
            'experience',
        ]

resumes/views.py
import json
from . import models
from users.decorators import user_is_employer
from resumes.forms import ResumeForm
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView, FormView
from django.views import View
from django.http import HttpResponseRedirect, JsonResponse
from django.core.urlresolvers import reverse_lazy
from django.utils.decorators import method_decorator


@method_decorator(login_required, name='dispatch')
@method_decorator(user_is_employer, name='dispatch')
class ResumeListView(ListView):
    queryset = models.Resume.objects.filter(status='published')


@method_decorator(login_required, name='dispatch')
class AddResumeView(FormView):
    template_name = 'resumes/add_resume.html'
    form_class = ResumeForm
    success_url = reverse_lazy('resumes:my_resumes')

    def form_valid(self, form):
        resume = form.save(commit=False)
        resume.creator = self.request.user
        resume.save()
        return super().form_valid(form)


# Просмотр страницы со всеми резюме текущего пользователя
@method_decorator(login_required, name='dispatch')
class MyResumesView(View):
    template_name = 'resumes/my_resumes.html'

    def get(self, request, *args, **kwargs):
        resumes = models.Resume.objects.filter(creator=request.user)
        return render(request, self.template_name, {'resumes': resumes})


@method_decorator(login_required, name='dispatch')
class ResumeDetailView(DetailView):
    model = models.Resume


class SetStatusView(View):
    def post(self, request, *args, **kwargs):
        data = json.loads(request.body)
        resume = models.Resume.objects.get(pk=data['resume'])
        resume.status = data['status']
        resume.save()
        return JsonResponse({
            'status': 'ok',
        })


class DeleteResumeView(View):
    def post(self, request, *args, **kwargs):
        resume = models.Resume.objects.get(pk=request.POST['resume'])
        resume.delete()
        return JsonResponse({
            'status': 'ok',
        })


@method_decorator(login_required, name='dispatch')
class ResumeUpdateView(UpdateView):
    model = models.Resume
    fields = ['email', 'title', 'location', 'photo', 'industry', 'summary', 'resume_file', 'skills', 'experience']
    template_name_suffix = '_update'

resumes/templates/resumes/add_resume.html
{% extends "antirabstvo/base.html" %}
{% block content %}
<form method="post" enctype="multipart/form-data" action="{% url 'resumes:add_resume' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-default">Добавить</button>
</form>
{% endblock content %}

resumes/templates/resumes/my_resumes.html
{% extends "antirabstvo/base.html" %}
{% block content %}
<a class="btn btn-primary" href="{% url 'resumes:add_resume' %}" style="margin-bottom:20px" role="button">Добавить резюме</a>
{% if resumes.count > 0 %}
<table class="table table-striped">
    <tr>
        <th>Заголовок резюме</th>
        <th>Статус</th>
        <th>Дата добавления</th>
        <th>Дата изменения</th>
        <th>Действия</th>
    </tr>
    {% for resume in resumes %}
    <tr id="resume-row-{{ resume.pk }}">
        <td><a href="{% url 'resumes:view_resume' resume.pk %}">{{ resume }}</a></td>
        <td id="status-{{ resume.pk }}">{{ resume.get_status_name }}</td>
        <td>{{ resume.date_created }}</td>
        <td>{{ resume.date_changed }}</td>
        <td>
            {% if resume.status == 'published' %}
                <a href="" id="hide" data-id="{{ resume.pk }}">Скрыть</a>
                <a href="" id="publish" style="display:none" data-id="{{ resume.pk }}">Опубликовать</a>
            {% else %}
                <a href="" id="hide" style="display:none" data-id="{{ resume.pk }}">Скрыть</a>
                <a href="" id="publish" data-id="{{ resume.pk }}">Опубликовать</a>
            {% endif %}
            <a href="{% url 'resumes:change_resume' resume.pk %}">Изменить</a>
            <a href="" id="delete" data-id="{{ resume.pk }}">Удалить</a>
        </td>
    </tr>
    {% endfor %}
</table>
{% endif %}
{% endblock content %}
{% block extra_scripts %}
<script>
    $('#hide').click(function(e){
        e.preventDefault();
        resume_id = $(this).data('id');
        $.post(
            "{% url 'resumes:set_status' %}",
            JSON.stringify({
                'resume': resume_id,
                'status': 'hidden'
            })
        ).done(function(msg){
            $('#status-'+resume_id).text('Скрыто');
            $('#hide').hide();
            $('#publish').show();
        });
    });
    $('#publish').click(function(e){
        e.preventDefault();
        resume_id = $(this).data('id');
        $.post(
            "{% url 'resumes:set_status' %}",
            JSON.stringify({
                'resume': resume_id,
                'status': 'published'
            })
        ).done(function(msg){
            $('#status-'+resume_id).text('Опубликовано');
            $('#hide').show();
            $('#publish').hide();
        });
    });
    $('#delete').click(function(e){
        e.preventDefault();
        id = $(this).data('id')
        $.post(
            "{% url 'resumes:delete_resume' %}",
            JSON.stringify({
                'resume': id,
            })
        ).done(function(msg){
            $('#resume-row-'+id).hide();
        });
        console.log($(this).closest(".status").val())
    });
</script>
{% endblock extra_scripts %}

resumes/templates/resumes/resume_detail.html
{% extends "antirabstvo/base.html" %}
{% block content %}
<p>{{ object.fio }}</p>
<p>{{ object.email }}</p>
<p>{{ object.title }}</p>
<p>{{ object.location }}</p>
<p>{{ object.photo }}</p>
<p>{{ object.industry }}</p>
<p>{{ object.summary }}</p>
<p><a href="{{ object.resume_file.url }}">Файл резюме</a></p>
<p>{{ object.skills }}</p>
<p>{{ object.experience }}</p>
<p>{{ object.date_created }}</p>
<p>{{ object.date_changed }}</p>
{% endblock content %}

resumes/templates/resumes/resume_list.html
{% extends "antirabstvo/base.html" %}
{% block content %}
{% if object_list.count > 0 %}
<table class="table table-striped">
    <tr>
        <th>Вопрос</th>
        <th>Дата добавления</th>
    </tr>
    {% for question in questions %}
    <tr>
        <td><a href="{% url 'questions:view_question' question.pk %}">{{ question }}</a></td>
        <td>{{ question.date_created }}</td>
    </tr>
    {% endfor %}
</table>
{% endif %}
{% endblock content %}

resumes/templates/resumes/resume_update.html
{% extends "antirabstvo/base.html" %}
{% block content %}
<form method="post" enctype="multipart/form-data" action="">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-default">Изменить</button>
</form>
{% endblock content %}